### ISSUE TITLE
Publish release that works with white ambiance lights

### ISSUE THREAD

**Issue by jodal** [kali/hue.rs#9]
I have a number of Hue lights with only white ambiance. The latest released version, 0.3.9, does not work with those, because the API does not include a `hue` attribute (and possibly others) in the listing of lights.

I've tested the latest version from git, and it seems to work nicely, thanks to PR #5. It would be really nice if this could be released to crates.io. Thanks :-)

**Comment by kali** [comment]
Of course ! Done. :)
